import { GameMode, TabuCard } from "../types";

// --- DEVASA VERİ HAVUZLARI ---

// Klasik Mod: Mevcut + Yeni Zor/Çok Zor Kelimeler
const CLASSIC_POOL: TabuCard[] = [
  // --- MEVCUT KOLAY/ORTA KELİMELER (~135 ADET) ---
  { target: "FUTBOL", forbidden: ["Top", "Kale", "Gol", "Maç", "Takım"] },
  { target: "GÜNEŞ", forbidden: ["Sarı", "Sıcak", "Yaz", "Gökyüzü", "Yıldız"] },
  { target: "TELEFON", forbidden: ["Aramak", "Konuşmak", "Mobil", "Alo", "Akıllı"] },
  { target: "OKUL", forbidden: ["Öğrenci", "Öğretmen", "Ders", "Sınıf", "Okumak"] },
  { target: "DOKTOR", forbidden: ["Hasta", "Hastane", "İlaç", "Muayene", "Beyaz Önlük"] },
  { target: "PİZZA", forbidden: ["İtalyan", "Hamur", "Peynir", "Yuvarlak", "Dilim"] },
  { target: "KEDİ", forbidden: ["Miyav", "Tüy", "Pati", "Köpek", "Evcil"] },
  { target: "DENİZ", forbidden: ["Su", "Mavi", "Yüzmek", "Balık", "Tuzlu"] },
  { target: "KİTAP", forbidden: ["Okumak", "Sayfa", "Yazar", "Roman", "Kütüphane"] },
  { target: "UÇAK", forbidden: ["Havalimanı", "Pilot", "Kanat", "Uçmak", "Yolcu"] },
  { target: "KAHVE", forbidden: ["İçmek", "Sıcak", "Kafein", "Fincan", "Türk"] },
  { target: "AYNA", forbidden: ["Bakmak", "Yansıma", "Cam", "Görmek", "Kendin"] },
  { target: "GÖZLÜK", forbidden: ["Göz", "Görmek", "Çerçeve", "Cam", "Takmak"] },
  { target: "SAAT", forbidden: ["Zaman", "Dakika", "Kol", "Duvar", "Geç"] },
  { target: "ÇİKOLATA", forbidden: ["Tatlı", "Kakaolu", "Şeker", "Yemek", "Bitter"] },
  { target: "İSTANBUL", forbidden: ["Boğaz", "Şehir", "Türkiye", "Köprü", "Deniz"] },
  { target: "ATATÜRK", forbidden: ["Lider", "Kurucu", "Türkiye", "Cumhuriyet", "Mustafa"] },
  { target: "BAYRAK", forbidden: ["Kırmızı", "Ay", "Yıldız", "Ülke", "Dalgalanmak"] },
  { target: "KARPUZ", forbidden: ["Yaz", "Kırmızı", "Çekirdek", "Kabuk", "Meyve"] },
  { target: "SİNEMA", forbidden: ["Film", "İzlemek", "Salon", "Patlamış Mısır", "Perde"] },
  { target: "ÖRÜMCEK", forbidden: ["Ağ", "Böcek", "Sekiz", "Korkmak", "Bacak"] },
  { target: "ŞEMSİYE", forbidden: ["Yağmur", "Islanmak", "Açmak", "Korumak", "Su"] },
  { target: "TERLİK", forbidden: ["Ayak", "Giymek", "Ev", "Yaz", "Parmak Arası"] },
  { target: "ÇAY", forbidden: ["İçmek", "Dem", "Bardak", "Kahvaltı", "Rize"] },
  { target: "DİŞ FIRÇASI", forbidden: ["Macun", "Temizlemek", "Ağız", "Sabah", "Fırçalamak"] },
  { target: "YASTIK", forbidden: ["Uyumak", "Yatak", "Baş", "Yumuşak", "Kılıf"] },
  { target: "BALIK", forbidden: ["Deniz", "Yüzmek", "Olta", "Pullu", "Akvaryum"] },
  { target: "GİTAR", forbidden: ["Müzik", "Tel", "Çalmak", "Enstrüman", "Akustik"] },
  { target: "KAMERA", forbidden: ["Fotoğraf", "Çekmek", "Resim", "Video", "Flash"] },
  { target: "SANDALYE", forbidden: ["Oturmak", "Masa", "Ayak", "Ahşap", "Mobilya"] },
  { target: "KELEBEK", forbidden: ["Tırtıl", "Uçmak", "Renkli", "Kanat", "Böcek"] },
  { target: "KAR", forbidden: ["Kış", "Soğuk", "Beyaz", "Yağmak", "Kardan Adam"] },
  { target: "YANGIN", forbidden: ["Ateş", "İtfaiye", "Yanmak", "Duman", "Sıcak"] },
  { target: "ÇİÇEK", forbidden: ["Gül", "Papatya", "Kokmak", "Bahçe", "Vazo"] },
  { target: "BİLGİSAYAR", forbidden: ["Ekran", "Klavye", "Mouse", "İnternet", "Oyun"] },
  { target: "DONDURMA", forbidden: ["Yaz", "Soğuk", "Külah", "Yalamak", "Maraş"] },
  { target: "GÖKKUŞAĞI", forbidden: ["Renk", "Yağmur", "Güneş", "Gökyüzü", "Yedi"] },
  { target: "HEMŞİRE", forbidden: ["Hastane", "Doktor", "İğne", "Yardım", "Sağlık"] },
  { target: "ASLAN", forbidden: ["Orman", "Kral", "Kükremek", "Yele", "Hayvan"] },
  { target: "TREN", forbidden: ["Ray", "Vagon", "Demiryolu", "İstasyon", "Hızlı"] },
  { target: "AYAKKABI", forbidden: ["Giymek", "Yürümek", "Bağcık", "Topuklu", "Spor"] },
  { target: "ÇÖL", forbidden: ["Kum", "Sıcak", "Deve", "Susuz", "Kaktüs"] },
  { target: "SİLGİ", forbidden: ["Silmek", "Kalem", "Kağıt", "Okul", "Hata"] },
  { target: "TAVŞAN", forbidden: ["Havuç", "Kulak", "Zıplamak", "Diş", "Hızlı"] },
  { target: "KARDAN ADAM", forbidden: ["Kış", "Havuç", "Soğuk", "Beyaz", "Yapmak"] },
  { target: "PİL", forbidden: ["Enerji", "Kumanda", "Bitmek", "Şarj", "Artı Eksi"] },
  { target: "ANAHTAR", forbidden: ["Kapı", "Kilit", "Açmak", "Çilingir", "Metal"] },
  { target: "SABUN", forbidden: ["Yıkamak", "El", "Köpük", "Temiz", "Banyo"] },
  { target: "MUZ", forbidden: ["Sarı", "Maymun", "Meyve", "Kabuk", "Soymak"] },
  { target: "HAMBURGER", forbidden: ["Fast Food", "Et", "Ekmek", "Patates", "Köfte"] },
  { target: "YILAN", forbidden: ["Sürünmek", "Zehir", "Uzun", "Dil", "Sokmak"] },
  { target: "PARA", forbidden: ["Lira", "Dolar", "Harcamak", "Cüzdan", "Kağıt"] },
  { target: "BERBER", forbidden: ["Saç", "Kesmek", "Tıraş", "Makas", "Erkek"] },
  { target: "ŞİMŞEK", forbidden: ["Gök Gürültüsü", "Çakmak", "Işık", "Yağmur", "Fırtına"] },
  { target: "TENCERE", forbidden: ["Yemek", "Pişirmek", "Kapak", "Mutfak", "Çelik"] },
  { target: "MİKROFON", forbidden: ["Ses", "Şarkı", "Konuşmak", "Sahne", "Karaoke"] },
  { target: "PALYAÇO", forbidden: ["Sirk", "Komik", "Burun", "Boyalı", "Güldürmek"] },
  { target: "YUMURTA", forbidden: ["Tavuk", "Kahvaltı", "Kırmak", "Beyaz", "Omlet"] },
  { target: "KALEM", forbidden: ["Yazmak", "Kağıt", "Kurşun", "Tükenmez", "Silgi"] },
  { target: "BALON", forbidden: ["Şişirmek", "Patlamak", "Uçmak", "Hava", "Renkli"] },
  { target: "AĞAÇ", forbidden: ["Orman", "Yaprak", "Dal", "Kök", "Yeşil"] },
  { target: "DÜĞÜN", forbidden: ["Gelin", "Damat", "Evlenmek", "Halay", "Takı"] },
  { target: "ASKER", forbidden: ["Ordu", "Silah", "Nöbet", "Komutan", "Kamuflaj"] },
  { target: "PENGUEN", forbidden: ["Kutup", "Buz", "Kuş", "Uçamaz", "Siyah Beyaz"] },
  { target: "KEMER", forbidden: ["Bel", "Pantolon", "Takmak", "Düşmek", "Toka"] },
  { target: "CADILAR BAYRAMI", forbidden: ["Balkabağı", "Korku", "Kostüm", "Şeker", "Ekim"] },
  { target: "NOEL BABA", forbidden: ["Hediye", "Yılbaşı", "Geyik", "Baca", "Sakal"] },
  { target: "KANGURU", forbidden: ["Avustralya", "Zıplamak", "Kese", "Yavru", "Hayvan"] },
  { target: "PİRAMİT", forbidden: ["Mısır", "Firavun", "Üçgen", "Mumya", "Tarihi"] },
  { target: "ROKET", forbidden: ["Uzay", "Fırlatmak", "Ay", "Astronot", "Hızlı"] },
  { target: "HAYALET", forbidden: ["Korku", "Ruh", "Beyaz", "Görünmez", "Boo"] },
  { target: "VAMPİR", forbidden: ["Kan", "Diş", "Isırmak", "Yarasa", "Sarımsak"] },
  { target: "ZOMBİ", forbidden: ["Ölü", "Yürümek", "Beyin", "Korku", "Film"] },
  { target: "UZAYLI", forbidden: ["Ufo", "Dünya Dışı", "Yeşil", "Uzay", "Uçan Daire"] },
  { target: "DENİZ KIZI", forbidden: ["Balık", "Kuyruk", "Masal", "Deniz", "Saç"] },
  { target: "EJDERHA", forbidden: ["Ateş", "Uçmak", "Masal", "Kanat", "Dev"] },
  { target: "BÜYÜCÜ", forbidden: ["Sihir", "Değnek", "Şapka", "Cadı", "Yapmak"] },
  { target: "PRENSES", forbidden: ["Taç", "Saray", "Masal", "Prens", "Güzel"] },
  { target: "KORSAN", forbidden: ["Gemi", "Hazine", "Kaptan", "Göz Bandı", "Kanca"] },
  { target: "ŞÖVALYE", forbidden: ["Zırh", "Kılıç", "At", "Ortaçağ", "Savaşçı"] },
  { target: "KOVBOY", forbidden: ["Şapka", "At", "Silah", "Vahşi Batı", "Çizme"] },
  { target: "AŞÇI", forbidden: ["Yemek", "Mutfak", "Şapka", "Pişirmek", "Restoran"] },
  { target: "POLİS", forbidden: ["Suçlu", "Hapis", "Üniforma", "Siren", "Yakalamak"] },
  { target: "İTFAİYECİ", forbidden: ["Yangın", "Su", "Hortum", "Kırmızı", "Kurtarmak"] },
  { target: "ASTRONOT", forbidden: ["Uzay", "Ay", "Kıyafet", "Roket", "Nasa"] },
  { target: "RESSAM", forbidden: ["Resim", "Fırça", "Tuval", "Boya", "Sanat"] },
  { target: "HAKEM", forbidden: ["Düdük", "Maç", "Kart", "Faul", "Futbol"] },
  { target: "KALECİ", forbidden: ["Gol", "Futbol", "Eldiven", "Tutmak", "Kale"] },
  { target: "ŞARKICI", forbidden: ["Mikrofon", "Sahne", "Ses", "Konser", "Müzik"] },
  { target: "OYUNCU", forbidden: ["Film", "Dizi", "Tiyatro", "Rol", "Sahne"] },
  { target: "YAZAR", forbidden: ["Kitap", "Kalem", "Hikaye", "Roman", "Yazmak"] },
  { target: "MÜHENDİS", forbidden: ["Bina", "Proje", "İnşaat", "Matematik", "Plan"] },
  { target: "AVUKAT", forbidden: ["Mahkeme", "Savunmak", "Hakim", "Dava", "Cübbe"] },
  { target: "PİLOT", forbidden: ["Uçak", "Uçmak", "Havalimanı", "Kokpit", "Kaptan"] },
  { target: "ŞOFÖR", forbidden: ["Araba", "Sürmek", "Direksiyon", "Yol", "Taksi"] },
  { target: "POSTACI", forbidden: ["Mektup", "Kargo", "Dağıtmak", "Haber", "Zarf"] },
  { target: "BAHÇIVAN", forbidden: ["Çiçek", "Toprak", "Sulamak", "Bahçe", "Bitki"] },
  { target: "TERZİ", forbidden: ["Dikmek", "İğne", "İplik", "Kumaş", "Elbise"] },
  { target: "KASAP", forbidden: ["Et", "Bıçak", "Kesmek", "Kıyma", "Pirzola"] },
  { target: "FIRINCI", forbidden: ["Ekmek", "Hamur", "Un", "Sıcak", "Pişirmek"] },
  { target: "KÜTÜPHANE", forbidden: ["Kitap", "Sessiz", "Okumak", "Raf", "Ödünç"] },
  { target: "HASTANE", forbidden: ["Doktor", "Hemşire", "Hasta", "Ambulans", "İlaç"] },
  { target: "MARKET", forbidden: ["Alışveriş", "Sepet", "Kasa", "Para", "Ürün"] },
  { target: "BANKA", forbidden: ["Para", "Hesap", "Kredi", "Kart", "Vezne"] },
  { target: "HAVAALANI", forbidden: ["Uçak", "Yolcu", "Bavul", "Uçuş", "Bilet"] },
  { target: "OTOBÜS", forbidden: ["Durak", "Yolcu", "Şoför", "Bilet", "Toplu Taşıma"] },
  { target: "TAKSİ", forbidden: ["Sarı", "Şoför", "Ücret", "Araba", "Gitmek"] },
  { target: "BİSİKLET", forbidden: ["Pedal", "İki Teker", "Sürmek", "Kask", "Zincir"] },
  { target: "MOTOSİKLET", forbidden: ["Kask", "Hızlı", "Motor", "İki Teker", "Ses"] },
  { target: "KAMYON", forbidden: ["Yük", "Taşımak", "Büyük", "Şoför", "Tekerlek"] },
  { target: "HELİKOPTER", forbidden: ["Pervane", "Uçmak", "Hava", "Pilot", "Ses"] },
  { target: "GEMİ", forbidden: ["Deniz", "Kaptan", "Liman", "Yolcu", "Büyük"] },
  { target: "SANDAL", forbidden: ["Kürek", "Deniz", "Kayık", "Balık", "Küçük"] },
  { target: "DENİZALTI", forbidden: ["Su Altı", "Dalmak", "Askeri", "Periskop", "Derin"] },
  { target: "ASANSÖR", forbidden: ["İnmek", "Çıkmak", "Kat", "Bina", "Düğme"] },
  { target: "MERDİVEN", forbidden: ["Basamak", "İnmek", "Çıkmak", "Yürümek", "Bina"] },
  { target: "BALKON", forbidden: ["Ev", "Dışarı", "Hava", "Çamaşır", "Manzara"] },
  { target: "ÇATI", forbidden: ["Ev", "En Üst", "Kiremit", "Baca", "Yağmur"] },
  { target: "BODRUM", forbidden: ["Alt Kat", "Karanlık", "Depo", "Eşya", "Ev"] },
  { target: "BAHÇE", forbidden: ["Çiçek", "Ağaç", "Çim", "Ev", "Toprak"] },
  { target: "HAVUZ", forbidden: ["Yüzmek", "Su", "Mavi", "Yaz", "Serinlemek"] },
  { target: "PARK", forbidden: ["Oyun", "Çocuk", "Salıncak", "Kaydırak", "Yürüyüş"] },
  { target: "ORMAN", forbidden: ["Ağaç", "Yeşil", "Hayvan", "Doğa", "Kamp"] },
  { target: "DAĞ", forbidden: ["Yüksek", "Tırmanmak", "Zirve", "Kar", "Tepe"] },
  { target: "MAĞARA", forbidden: ["Karanlık", "İn", "Ayı", "Yarasa", "Taş"] },
  { target: "ŞELALE", forbidden: ["Su", "Akmak", "Yüksek", "Dökülmek", "Nehir"] },
  { target: "NEHİR", forbidden: ["Su", "Akmak", "Irmak", "Deniz", "Balık"] },
  { target: "GÖL", forbidden: ["Su", "Durgun", "Ördek", "Piknik", "Kenar"] },
  { target: "ADA", forbidden: ["Deniz", "Kara", "Dört Taraf", "Issız", "Yüzmek"] },
  { target: "PLAJ", forbidden: ["Kum", "Deniz", "Güneş", "Yaz", "Şemsiye"] },
  { target: "YANARDAĞ", forbidden: ["Lav", "Patlamak", "Ateş", "Volkan", "Dağ"] },
  { target: "DEPREM", forbidden: ["Sarsıntı", "Yıkılmak", "Fay", "Doğal Afet", "Korku"] },
  { target: "SEL", forbidden: ["Su", "Yağmur", "Taşmak", "Afet", "Zarar"] },
  { target: "ÇIĞ", forbidden: ["Kar", "Düşmek", "Dağ", "Beyaz", "Tehlike"] },
  { target: "FIRTIINA", forbidden: ["Rüzgar", "Yağmur", "Şimşek", "Hava", "Güçlü"] },
  { target: "HORTUM", forbidden: ["Rüzgar", "Dönmek", "Afet", "Hava", "Yıkıcı"] },
  { target: "SİS", forbidden: ["Duman", "Görmek", "Beyaz", "Hava", "Bulut"] },
  { target: "DOLU", forbidden: ["Yağış", "Buz", "Sert", "Hava", "Zarar"] },
  { target: "BULUT", forbidden: ["Gökyüzü", "Beyaz", "Pamuk", "Yağmur", "Hava"] },
  { target: "YILDIZ", forbidden: ["Gece", "Gökyüzü", "Parlak", "Kayan", "Uzay"] },
  { target: "AY", forbidden: ["Gece", "Gökyüzü", "Hilal", "Dolunay", "Uydu"] },
  { target: "DÜNYA", forbidden: ["Gezegen", "Yaşam", "Yuvarlak", "Mavi", "Biz"] },
  { target: "MARS", forbidden: ["Gezegen", "Kızıl", "Uzay", "Komşu", "Dünya"] },
  { target: "SATÜRN", forbidden: ["Halka", "Gezegen", "Uzay", "Gaz", "Sistem"] },
  { target: "JÜPİTER", forbidden: ["Büyük", "Gezegen", "Gaz", "Sistem", "Uzay"] },
  { target: "GÖKTAŞI", forbidden: ["Taş", "Uzay", "Düşmek", "Meteor", "Krater"] },
  { target: "KARA DELİK", forbidden: ["Uzay", "Çekim", "Karanlık", "Işık", "Yutmak"] },
  { target: "TELESKOP", forbidden: ["Bakmak", "Uzay", "Yıldız", "Büyütmek", "Gözlem"] },
  { target: "MİKROSKOP", forbidden: ["Küçük", "Büyütmek", "İncelemek", "Laboratuvar", "Bakteri"] },
  { target: "TERMOMETRE", forbidden: ["Sıcaklık", "Ölçmek", "Derece", "Ateş", "Hava"] },
  { target: "PUSULA", forbidden: ["Yön", "Kuzey", "Güney", "İğne", "Harita"] },
  { target: "KÜRE", forbidden: ["Dünya", "Yuvarlak", "Harita", "Model", "Dönmek"] },
  { target: "BAYKUŞ", forbidden: ["Kuş", "Gece", "Göz", "Uçmak", "Bilge"] },
  { target: "KARTAL", forbidden: ["Kuş", "Yırtıcı", "Uçmak", "Yüksek", "Pençe"] },
  { target: "PAPAĞAN", forbidden: ["Kuş", "Konuşmak", "Renkli", "Tekrar", "Kafes"] },
  { target: "SERÇE", forbidden: ["Kuş", "Küçük", "Minik", "Cik Cik", "Uçmak"] },
  { target: "GÜVERCİN", forbidden: ["Kuş", "Barış", "Haber", "Posta", "Uçmak"] },
  { target: "TAVUK", forbidden: ["Yumurta", "Kümes", "Horoz", "Kuş", "Kanat"] },
  { target: "HOROZ", forbidden: ["Sabah", "Ötmek", "Tavuk", "Kümes", "Erken"] },
  { target: "İNEK", forbidden: ["Süt", "Ot", "Çiftlik", "Siyah Beyaz", "Möö"] },
  { target: "KOYUN", forbidden: ["Yün", "Ot", "Çoban", "Sürü", "Melemek"] },
  { target: "KEÇİ", forbidden: ["İnatçı", "Boynuz", "Ot", "Sakal", "Tırmanmak"] },
  { target: "AT", forbidden: ["Binmek", "Yarış", "Nal", "Yele", "Dörtnala"] },
  { target: "EŞEK", forbidden: ["İnatçı", "Yük", "Kulak", "Hayvan", "Göz"] },
  { target: "DEVE", forbidden: ["Hörgüç", "Çöl", "Su", "Taşımak", "Uzun"] },
  { target: "FİL", forbidden: ["Hortum", "Büyük", "Kulak", "Diş", "Afrika"] },
  { target: "ZÜRAFA", forbidden: ["Boyun", "Uzun", "Benekli", "Ağaç", "Afrika"] },
  { target: "MAYMUN", forbidden: ["Muz", "Ağaç", "Tırmanmak", "Orman", "İnsan"] },
  { target: "AYI", forbidden: ["Bal", "Kış Uykusu", "Orman", "Kürk", "Pençe"] },
  { target: "KURT", forbidden: ["Ulumak", "Sürü", "Ay", "Orman", "Vahşi"] },
  { target: "TİLKİ", forbidden: ["Kurnaz", "Kuyruk", "Turuncu", "Orman", "Hayvan"] },
  { target: "SİNCAP", forbidden: ["Ceviz", "Fındık", "Kuyruk", "Ağaç", "Kemirmek"] },
  { target: "KİRPİ", forbidden: ["Diken", "Küçük", "Top", "Hayvan", "Batmak"] },
  { target: "KAPLUMBAĞA", forbidden: ["Kabuk", "Yavaş", "Yeşil", "Yürümek", "Hayvan"] },
  { target: "TİMSAH", forbidden: ["Nehir", "Diş", "Yeşil", "Tehlikeli", "Sürüngen"] },
  { target: "KURBAĞA", forbidden: ["Zıplamak", "Yeşil", "Su", "Prens", "Vırak"] },
  { target: "ARABA", forbidden: ["Tekerlek", "Direksiyon", "Sürmek", "Marka", "Yol"] },
  { target: "BİLGİSAYAR OYUNU", forbidden: ["Oynamak", "Konsol", "Klavye", "Eğlence", "Sanal"] },
  { target: "KOLTUK", forbidden: ["Oturmak", "Salon", "Rahat", "Mobilya", "Yastık"] },
  { target: "HALI", forbidden: ["Yer", "Sermek", "Dokuma", "Desen", "Yün"] },
  { target: "PERDE", forbidden: ["Pencere", "Kumaş", "Kapatmak", "Güneş", "Korniş"] },
  { target: "ÜTÜ", forbidden: ["Kıyafet", "Sıcak", "Düzeltmek", "Buhar", "Kırışık"] },
  { target: "ÇAMAŞIR MAKİNESİ", forbidden: ["Yıkamak", "Kıyafet", "Su", "Deterjan", "Temiz"] },
  { target: "BULAŞIK MAKİNESİ", forbidden: ["Mutfak", "Tabak", "Bardak", "Yıkamak", "Temiz"] },
  { target: "BUZDOLABI", forbidden: ["Soğuk", "Yiyecek", "Mutfak", "Saklamak", "Kapak"] },
  { target: "OCAK", forbidden: ["Ateş", "Yemek", "Pişirmek", "Gaz", "Mutfak"] },
  { target: "SÜPÜRGE", forbidden: ["Temizlemek", "Toz", "Elektrikli", "Ev", "Çekmek"] },
  { target: "PASPAS", forbidden: ["Silmek", "Yer", "Islak", "Temizlik", "Kova"] },
  { target: "ÇÖP KUTUSU", forbidden: ["Atmak", "Pis", "Poşet", "Kova", "Geri Dönüşüm"] },
  { target: "VAZO", forbidden: ["Çiçek", "Su", "Masa", "Cam", "Dekor"] },
  { target: "TABLO", forbidden: ["Resim", "Duvar", "Sanat", "Çerçeve", "Boyamak"] },
  { target: "MÜZE", forbidden: ["Tarihi", "Eser", "Gezmek", "Eski", "Sanat"] },
  { target: "LABORATUVAR", forbidden: ["Deney", "Bilim", "Önlük", "Tüp", "Araştırma"] },
  { target: "ECZANE", forbidden: ["İlaç", "Hasta", "Reçete", "Sağlık", "Almak"] },
  { target: "PASTANE", forbidden: ["Tatlı", "Pasta", "Kek", "Kurabiye", "Şeker"] },
  { target: "MANAV", forbidden: ["Meyve", "Sebze", "Taze", "Satmak", "Domates"] },
  { target: "KUAFÖR", forbidden: ["Saç", "Kesmek", "Fön", "Boya", "Kadın"] },
  { target: "AYAKKABICI", forbidden: ["Ayakkabı", "Tamir", "Satmak", "Deri", "Numara"] },
  { target: "KIRTASİYE", forbidden: ["Kalem", "Defter", "Okul", "Silgi", "Kağıt"] },
  { target: "OYUNCAK", forbidden: ["Çocuk", "Oynamak", "Bebek", "Araba", "Eğlence"] },
  { target: "HEDİYE", forbidden: ["Paket", "Vermek", "Sürpriz", "Doğum Günü", "Mutlu"] },
  { target: "DOĞUM GÜNÜ", forbidden: ["Pasta", "Mum", "Kutlamak", "Parti", "Yaş"] },
  { target: "YILBAŞI", forbidden: ["Yeni Yıl", "Aralık", "Ocak", "Kutlama", "Ağaç"] },
  { target: "BAYRAM", forbidden: ["Tatil", "El Öpmek", "Şeker", "Ziyaret", "Akraba"] },
  { target: "TATİL", forbidden: ["Deniz", "Yaz", "Dinlenmek", "Okul", "Gezmek"] },
  { target: "PİKNİK", forbidden: ["Yemek", "Orman", "Örtü", "Mangal", "Hafta Sonu"] },
  { target: "MANGAL", forbidden: ["Et", "Ateş", "Duman", "Pişirmek", "Piknik"] },
  { target: "KAMP", forbidden: ["Çadır", "Ateş", "Orman", "Doğa", "Uyku Tulumu"] },
  { target: "BALIK TUTMAK", forbidden: ["Olta", "Deniz", "Göl", "Balık", "Sabır"] },
  { target: "YÜZMEK", forbidden: ["Su", "Deniz", "Havuz", "Kulaç", "Spor"] },
  { target: "KOŞMAK", forbidden: ["Hızlı", "Spor", "Yürümek", "Yarış", "Terlemek"] },
  { target: "YÜRÜMEK", forbidden: ["Ayak", "Yol", "Spor", "Adım", "Gezmek"] },
  { target: "UYUMAK", forbidden: ["Gece", "Yatak", "Rüya", "Göz", "Dinlenmek"] },
  { target: "RÜYA", forbidden: ["Uyumak", "Görmek", "Gece", "Hayal", "Gerçek"] },
  { target: "KABUS", forbidden: ["Korku", "Rüya", "Uyanmak", "Kötü", "Gece"] },
  { target: "SEVGİ", forbidden: ["Aşk", "Kalp", "His", "Sevmek", "Duygu"] },
  { target: "KORKU", forbidden: ["Ürkmek", "Karanlık", "Kaçmak", "His", "Bağırmak"] },
  { target: "MUTLULUK", forbidden: ["Gülmek", "Sevinç", "His", "Güzel", "Neşe"] },
  { target: "ÜZÜNTÜ", forbidden: ["Ağlamak", "Mutsuz", "Kötü", "His", "Gözyaşı"] },
  { target: "ÖFKE", forbidden: ["Kızmak", "Sinir", "Bağırmak", "Kavga", "His"] },
  { target: "ŞAŞIRMAK", forbidden: ["Beklenmedik", "Sürpriz", "Hayret", "Göz", "Ağız"] },
  { target: "GÜLMEK", forbidden: ["Komik", "Eğlence", "Kahkaha", "Mutlu", "Ağız"] },
  { target: "AĞLAMAK", forbidden: ["Gözyaşı", "Üzülmek", "Göz", "Duygu", "Bebek"] },
  { target: "DÜŞÜNMEK", forbidden: ["Beyin", "Akıl", "Fikir", "Kafa", "Soru"] },
  { target: "UNUTMAK", forbidden: ["Hatırlamak", "Hafıza", "Akıl", "Bilmemek", "Kaybetmek"] },
  { target: "HATIRLAMAK", forbidden: ["Unutmak", "Hafıza", "Eski", "Anı", "Bilmek"] },
  { target: "ÖĞRENMEK", forbidden: ["Okul", "Bilgi", "Ders", "Çalışmak", "Bilmek"] },
  { target: "ÇALIŞMAK", forbidden: ["İş", "Ders", "Yorulmak", "Para", "Meslek"] },
  { target: "DİNLENMEK", forbidden: ["Yorulmak", "Uyumak", "Tatil", "Oturmak", "Rahat"] },
  { target: "YEMEK YEMEK", forbidden: ["Aç", "Mide", "Sofra", "Kaşık", "Ağız"] },
  { target: "SU İÇMEK", forbidden: ["Susuzluk", "Bardak", "Şişe", "Sıvı", "Kana Kana"] },
  { target: "KONUŞMAK", forbidden: ["Ses", "Ağız", "Dil", "Sohbet", "Anlatmak"] },
  { target: "DİNLEMEK", forbidden: ["Kulak", "Ses", "Duymak", "Müzik", "Sessiz"] },
  { target: "YAZMAK", forbidden: ["Kalem", "Kağıt", "Harf", "Okumak", "Not"] },
  { target: "OKUMAK", forbidden: ["Kitap", "Göz", "Harf", "Yazı", "Anlamak"] },
  { target: "BOYAMAK", forbidden: ["Renk", "Fırça", "Resim", "Kalem", "Duvar"] },
  { target: "KESMEK", forbidden: ["Makas", "Bıçak", "Kağıt", "Saç", "Parça"] },
  { target: "YAPIŞTIRMAK", forbidden: ["Yapıştırıcı", "Bant", "Kağıt", "Birleştirmek", "Tutkal"] },
  { target: "PİYANO", forbidden: ["Tuş", "Müzik", "Siyah Beyaz", "Çalmak", "Büyük"] },
  { target: "KEMAN", forbidden: ["Yay", "Müzik", "Çalmak", "Omuz", "Ses"] },
  { target: "DAVUL", forbidden: ["Vurmak", "Tokmak", "Müzik", "Ritim", "Ses"] },
  { target: "FLÜT", forbidden: ["Üflemek", "Müzik", "Delik", "Ses", "Okul"] },
  { target: "KONSER", forbidden: ["Müzik", "Şarkıcı", "Sahne", "Kalabalık", "Bilet"] },
  { target: "TİYATRO", forbidden: ["Sahne", "Oyuncu", "Perde", "İzleyici", "Oyun"] },
  { target: "RESİM", forbidden: ["Boya", "Fırça", "Çizmek", "Sanat", "Tablo"] },
  { target: "DANS", forbidden: ["Müzik", "Oynamak", "Hareket", "Bale", "Tango"] },
  { target: "ŞARKI", forbidden: ["Söylemek", "Müzik", "Ses", "Dinlemek", "Melodi"] },
  { target: "ŞİİR", forbidden: ["Şair", "Kıta", "Mısra", "Yazmak", "Okumak"] },
  { target: "ROMAN", forbidden: ["Kitap", "Yazar", "Okumak", "Hikaye", "Uzun"] },
  { target: "MASAL", forbidden: ["Çocuk", "Anlatmak", "Prenses", "Dev", "Uyku"] },
  { target: "HİKAYE", forbidden: ["Kısa", "Anlatmak", "Olay", "Kitap", "Yazı"] },
  { target: "GAZETE", forbidden: ["Haber", "Okumak", "Kağıt", "Günlük", "Manşet"] },
  { target: "DERGİ", forbidden: ["Kapak", "Sayfa", "Resim", "Okumak", "Aylık"] },
  { target: "TELEVİZYON", forbidden: ["İzlemek", "Ekran", "Kumanda", "Dizi", "Haber"] },
  { target: "RADYO", forbidden: ["Dinlemek", "Ses", "Müzik", "Frekans", "Haber"] },
  { target: "İNTERNET", forbidden: ["Bilgisayar", "Wifi", "Web", "Site", "Bağlanmak"] },
  { target: "SOSYAL MEDYA", forbidden: ["Paylaşmak", "Beğeni", "Takip", "Fotoğraf", "İnternet"] },
  { target: "MESAJ", forbidden: ["Yazmak", "Göndermek", "Telefon", "Sms", "Okumak"] },
  { target: "E-POSTA", forbidden: ["Mail", "Bilgisayar", "Göndermek", "İnternet", "Mektup"] },
  { target: "MEKTUP", forbidden: ["Zarf", "Posta", "Kağıt", "Yazmak", "Pul"] },
  { target: "KARGO", forbidden: ["Paket", "Taşımak", "Getirmek", "Kutu", "Sipariş"] },
  { target: "ADRES", forbidden: ["Ev", "Sokak", "Numara", "Bulmak", "Tarif"] },
  { target: "PASAPORT", forbidden: ["Yurt Dışı", "Seyahat", "Vize", "Kimlik", "Havaalanı"] },
  { target: "BİLET", forbidden: ["Uçak", "Sinema", "Otobüs", "Konser", "Girmek"] },
  { target: "KREDİ KARTI", forbidden: ["Banka", "Plastik", "Ödemek", "Şifre", "Para"] },
  { target: "CÜZDAN", forbidden: ["Para", "Kart", "Cep", "Deri", "Taşımak"] },
  { target: "ÇANTA", forbidden: ["Sırt", "Kol", "Eşya", "Okul", "Taşımak"] },
  { target: "BAVUL", forbidden: ["Seyahat", "Eşya", "Kıyafet", "Tekerlek", "Tatil"] },
  { target: "KOLYE", forbidden: ["Boyun", "Takı", "Zincir", "Altın", "Gümüş"] },
  { target: "YÜZÜK", forbidden: ["Parmak", "Evlilik", "Nişan", "Takı", "Altın"] },
  { target: "KÜPE", forbidden: ["Kulak", "Delik", "Takı", "Kadın", "Aksesuar"] },
  { target: "BİLEZİK", forbidden: ["Kol", "Bilek", "Altın", "Takı", "Kadın"] },
  { target: "ŞAPKA", forbidden: ["Baş", "Takmak", "Güneş", "Kış", "Bere"] },
  { target: "ELDİVEN", forbidden: ["El", "Kış", "Soğuk", "Takmak", "Parmak"] },
  { target: "ATKI", forbidden: ["Boyun", "Kış", "Soğuk", "Örgü", "Sarmak"] },
  { target: "MONT", forbidden: ["Kış", "Giyim", "Soğuk", "Fermuar", "Kalın"] },
  { target: "CEKET", forbidden: ["Giyim", "Takım Elbise", "Düğme", "Üst", "Kıyafet"] },
  { target: "GÖMLEK", forbidden: ["Yaka", "Düğme", "Ütü", "Kıyafet", "Erkek"] },
  { target: "TİŞÖRT", forbidden: ["Yaz", "Kısa Kol", "Giyim", "Penye", "Üst"] },
  { target: "PANTOLON", forbidden: ["Bacak", "Kot", "Giyim", "Kemer", "Alt"] },
  { target: "ETEK", forbidden: ["Kadın", "Giyim", "Kısa", "Uzun", "Bacak"] },
  { target: "ELBİSE", forbidden: ["Kadın", "Tek Parça", "Giyim", "Düğün", "Abiye"] },
  { target: "ÇORAP", forbidden: ["Ayak", "Giyim", "Çift", "Yün", "Giymek"] },

  // --- YENİ EKLENEN ZOR KELİMELER (GÜNCEL & TEKNOLOJİK) (~135 ADET) ---
  { target: "YAPAY ZEKA", forbidden: ["Robot", "Bilgisayar", "Akıl", "Teknoloji", "Gelecek"] },
  { target: "METAVERSE", forbidden: ["Sanal", "Evren", "Gözlük", "Facebook", "Oyun"] },
  { target: "KRİPTO PARA", forbidden: ["Bitcoin", "Borsa", "Sanal", "Yatırım", "Blockchain"] },
  { target: "NFT", forbidden: ["Resim", "Dijital", "Sanat", "Satmak", "Token"] },
  { target: "DRONE", forbidden: ["Uçmak", "Kamera", "Uzaktan", "Kumanda", "Hava"] },
  { target: "INFLUENCER", forbidden: ["Sosyal Medya", "Takipçi", "Ünlü", "Instagram", "Reklam"] },
  { target: "SELFIE", forbidden: ["Fotoğraf", "Çekmek", "Özçekim", "Telefon", "Kamera"] },
  { target: "PODCAST", forbidden: ["Dinlemek", "Radyo", "Ses", "Program", "Yayın"] },
  { target: "VLOG", forbidden: ["Video", "Blog", "YouTube", "Çekmek", "Günlük"] },
  { target: "STREAMING", forbidden: ["Yayın", "Canlı", "Netflix", "İzlemek", "Platform"] },
  { target: "E-SPOR", forbidden: ["Oyun", "Bilgisayar", "Turnuva", "Oyuncu", "Takım"] },
  { target: "STARTUP", forbidden: ["Girişim", "Şirket", "Yeni", "Yatırım", "Fikir"] },
  { target: "FREELANCE", forbidden: ["Çalışmak", "Serbest", "Ev", "Ofis", "Bağımsız"] },
  { target: "HOME OFFICE", forbidden: ["Ev", "Çalışmak", "İş", "Bilgisayar", "Ofis"] },
  { target: "Z KUŞAĞI", forbidden: ["Genç", "Nesil", "Teknoloji", "İnternet", "Yaş"] },
  { target: "PANDEMİ", forbidden: ["Salgın", "Hastalık", "Maske", "Virüs", "Dünya"] },
  { target: "KARANTİNA", forbidden: ["Ev", "Çıkmak", "Yasak", "Hastalık", "İzole"] },
  { target: "AŞI", forbidden: ["İğne", "Koruma", "Hastalık", "Doktor", "Hemşire"] },
  { target: "VİRÜS", forbidden: ["Hastalık", "Mikrop", "Bulaşmak", "Bilgisayar", "Hasta"] },
  { target: "BAĞIŞIKLIK", forbidden: ["Sistem", "Güçlü", "Hasta", "Vücut", "Direnç"] },
  { target: "SİBER GÜVENLİK", forbidden: ["Hacker", "Koruma", "Bilgisayar", "Saldırı", "Şifre"] },
  { target: "BLOKZİNCİR", forbidden: ["Kripto", "Veri", "Güvenlik", "Halka", "Teknoloji"] },
  { target: "BULUT BİLİŞİM", forbidden: ["Depolama", "İnternet", "Veri", "Sunucu", "Sanal"] },
  { target: "BÜYÜK VERİ", forbidden: ["Analiz", "Bilgi", "İnternet", "Şirket", "İstatistik"] },
  { target: "NESNELERİN İNTERNETİ", forbidden: ["Cihaz", "Bağlantı", "Akıllı", "Ev", "Kontrol"] },
  { target: "GİYİLEBİLİR TEKNOLOJİ", forbidden: ["Saat", "Gözlük", "Akıllı", "Vücut", "Sensör"] },
  { target: "SANAL GERÇEKLİK", forbidden: ["Gözlük", "Oyun", "Dünya", "Simülasyon", "3D"] },
  { target: "ARTIRILMIŞ GERÇEKLİK", forbidden: ["Telefon", "Kamera", "Pokemon", "Görüntü", "Eklemek"] },
  { target: "OTONOM", forbidden: ["Sürücüsüz", "Araba", "Kendi", "Otomatik", "Robot"] },
  { target: "ALGORİTMA", forbidden: ["Kod", "Mantık", "Program", "Sıralama", "Matematik"] },
  { target: "KODLAMA", forbidden: ["Yazılım", "Bilgisayar", "Program", "Dil", "Script"] },
  { target: "UYGULAMA", forbidden: ["Telefon", "İndirmek", "Oyun", "App", "Market"] },
  { target: "BİLDİRİM", forbidden: ["Telefon", "Ses", "Mesaj", "Haber", "Uyarı"] },
  { target: "KONUM", forbidden: ["GPS", "Harita", "Yer", "Adres", "Paylaşmak"] },
  { target: "WIFI", forbidden: ["İnternet", "Kablosuz", "Bağlantı", "Şifre", "Modem"] },
  { target: "BLUETOOTH", forbidden: ["Bağlantı", "Kablosuz", "Kulaklık", "Veri", "Mavi"] },
  { target: "POWERBANK", forbidden: ["Şarj", "Pil", "Taşınabilir", "Telefon", "Enerji"] },
  { target: "AKILLI SAAT", forbidden: ["Kol", "Zaman", "Adım", "Telefon", "Bildirim"] },
  { target: "TABLET", forbidden: ["Ekran", "Bilgisayar", "Dokunmatik", "Büyük", "iPad"] },
  { target: "LAPTOP", forbidden: ["Bilgisayar", "Dizüstü", "Taşınabilir", "Klavye", "Ekran"] },
  { target: "KULAKLIK", forbidden: ["Müzik", "Ses", "Dinlemek", "Kulağa", "Takmak"] },
  { target: "HOPARLÖR", forbidden: ["Ses", "Müzik", "Yüksek", "Bass", "Parti"] },
  { target: "KLAVYE", forbidden: ["Yazmak", "Tuş", "Bilgisayar", "Q", "F"] },
  { target: "MOUSE", forbidden: ["Fare", "Tıklamak", "Bilgisayar", "İmleç", "Kaydırmak"] },
  { target: "EKRAN", forbidden: ["Görüntü", "Monitör", "Televizyon", "Telefon", "Cam"] },
  { target: "PİKSEL", forbidden: ["Görüntü", "Nokta", "Çözünürlük", "Ekran", "Kare"] },
  { target: "ÇÖZÜNÜRLÜK", forbidden: ["Kalite", "Ekran", "HD", "4K", "Netlik"] },
  { target: "FORMAT", forbidden: ["Sıfırlamak", "Bilgisayar", "Silmek", "Kurulum", "Windows"] },
  { target: "GÜNCELLEME", forbidden: ["Yeni", "Sürüm", "Yüklemek", "Telefon", "İyileştirme"] },
  { target: "HESAP", forbidden: ["Profil", "Giriş", "Şifre", "Banka", "Kullanıcı"] },
  { target: "ŞİFRE", forbidden: ["Gizli", "Giriş", "Güvenlik", "Parola", "Kod"] },
  { target: "KULLANICI ADI", forbidden: ["Profil", "İsim", "Giriş", "Nick", "Hesap"] },
  { target: "PROFİL", forbidden: ["Resim", "Hesap", "Bilgi", "Sosyal Medya", "Sayfa"] },
  { target: "TAKİPÇİ", forbidden: ["Sosyal Medya", "Instagram", "Kişi", "Sayı", "Fenomen"] },
  { target: "BEĞENİ", forbidden: ["Kalp", "Like", "Buton", "Sosyal Medya", "Popüler"] },
  { target: "YORUM", forbidden: ["Yazmak", "Fikir", "Alt", "Cevap", "Eleştiri"] },
  { target: "PAYLAŞIM", forbidden: ["Gönderi", "Fotoğraf", "Video", "Post", "Arkadaş"] },
  { target: "ENGEL", forbidden: ["Yasak", "Görmemek", "Kişi", "Sosyal Medya", "Blok"] },
  { target: "ETİKET", forbidden: ["Hashtag", "Konu", "İsim", "İşaret", "#"] },
  { target: "LİNK", forbidden: ["Adres", "Tıklamak", "Site", "Bağlantı", "URL"] },
  { target: "TARAYICI", forbidden: ["İnternet", "Chrome", "Girmek", "Site", "Web"] },
  { target: "ARAMA MOTORU", forbidden: ["Google", "Bulmak", "Yazmak", "Sonuç", "İnternet"] },
  { target: "SOSYAL AĞ", forbidden: ["İletişim", "Arkadaş", "Medya", "Platform", "Site"] },
  { target: "FENOMEN", forbidden: ["Ünlü", "İnternet", "Takipçi", "Popüler", "Video"] },
  { target: "VİRAL", forbidden: ["Yayılmak", "Popüler", "Video", "Hızlı", "İnternet"] },
  { target: "TREND", forbidden: ["Moda", "Popüler", "Gündem", "Liste", "Konu"] },
  { target: "MEME", forbidden: ["Komik", "Resim", "Yazı", "İnternet", "Caps"] },
  { target: "EMOJİ", forbidden: ["Yüz", "İfade", "Sarı", "Mesaj", "Duygu"] },
  { target: "GIF", forbidden: ["Hareketli", "Resim", "Video", "Kısa", "Komik"] },
  { target: "STICKER", forbidden: ["Çıkartma", "Yapıştırmak", "Mesaj", "Resim", "Whatsapp"] },
  { target: "GRUP", forbidden: ["Whatsapp", "Arkadaş", "Sohbet", "Topluluk", "Mesaj"] },
  { target: "ADMİN", forbidden: ["Yönetici", "Grup", "Site", "Kontrol", "Yetki"] },
  { target: "MODERATÖR", forbidden: ["Düzen", "Yönetici", "Forum", "Denetim", "Ceza"] },
  { target: "BAN", forbidden: ["Yasak", "Atılmak", "Oyun", "Forum", "Süre"] },
  { target: "SPAM", forbidden: ["Gereksiz", "Tekrar", "Mesaj", "Reklam", "Posta"] },
  { target: "FAKE", forbidden: ["Sahte", "Gerçek", "Hesap", "Yalan", "Kişi"] },
  { target: "STALKER", forbidden: ["Takip", "Gizli", "Bakmak", "Profil", "Eski Sevgili"] },
  { target: "SPOILER", forbidden: ["Bilgi", "Film", "Son", "Söylemek", "Sürpriz"] },
  { target: "TROLL", forbidden: ["Şaka", "Kızdırmak", "İnternet", "Yorum", "Komik"] },
  { target: "CAPS", forbidden: ["Komik", "Resim", "Yazı", "Kırmızı Şerit", "Mizah"] },
  { target: "YOUTUBER", forbidden: ["Video", "Kanal", "Abone", "İzlenme", "Para"] },
  { target: "GAMER", forbidden: ["Oyun", "Oyuncu", "Bilgisayar", "Konsol", "Yayıncı"] },
  { target: "YAYINCI", forbidden: ["Canlı", "Twitch", "İzleyici", "Kamera", "Oyun"] },
  { target: "ABONE", forbidden: ["Kanal", "Takip", "Üye", "YouTube", "Bildirim"] },
  { target: "PLAZA", forbidden: ["Bina", "İş", "Ofis", "Beyaz Yaka", "Yüksek"] },
  { target: "TOPLANTI", forbidden: ["İş", "Konuşmak", "Masa", "Patron", "Sunum"] },
  { target: "SUNUM", forbidden: ["Slayt", "Anlatmak", "Proje", "Powerpoint", "Toplantı"] },
  { target: "RAPOR", forbidden: ["Yazı", "Bilgi", "İş", "Sonuç", "Hazırlamak"] },
  { target: "MAAŞ", forbidden: ["Para", "Ay", "Çalışmak", "Ödeme", "Hesap"] },
  { target: "PRİM", forbidden: ["Ekstra", "Para", "Başarı", "Satış", "Ödül"] },
  { target: "TERFİ", forbidden: ["Yükselmek", "İş", "Müdür", "Başarı", "Kariyer"] },
  { target: "İSTİFA", forbidden: ["Bırakmak", "İş", "Gitmek", "Dilekçe", "Ayrılmak"] },
  { target: "MÜLAKAT", forbidden: ["İş", "Görüşme", "Soru", "Cevap", "İşe Alım"] },
  { target: "CV", forbidden: ["Özgeçmiş", "İş", "Başvuru", "Belge", "Tecrübe"] },
  { target: "KARİYER", forbidden: ["İş", "Gelecek", "Meslek", "Başarı", "Plan"] },
  { target: "OFİS", forbidden: ["Çalışmak", "Masa", "Bilgisayar", "Yer", "İşyeri"] },
  { target: "MESAİ", forbidden: ["Saat", "Çalışmak", "Fazla", "İş", "Akşam"] },
  { target: "İZİN", forbidden: ["Tatil", "Çalışmamak", "Gün", "Rapor", "Yıllık"] },
  { target: "STAJYER", forbidden: ["Öğrenci", "Yeni", "İş", "Tecrübe", "Genç"] },
  { target: "PATRON", forbidden: ["Yönetici", "Şirket", "Sahip", "Emir", "İşveren"] },
  { target: "MÜDÜR", forbidden: ["Yönetici", "Sorumlu", "Yetkili", "Oda", "İmza"] },
  { target: "ŞİRKET", forbidden: ["Firma", "Kurum", "İş", "Ticaret", "Ofis"] },
  { target: "HOLDİNG", forbidden: ["Büyük", "Şirketler", "Grup", "Patron", "Ticaret"] },
  { target: "CEO", forbidden: ["Yönetici", "Başkan", "Şirket", "En Üst", "Lider"] },
  { target: "GİRİŞİMCİ", forbidden: ["Fikir", "İş", "Kurmak", "Risk", "Para"] },
  { target: "YATIRIM", forbidden: ["Para", "Gelecek", "Kazanç", "Risk", "Borsa"] },
  { target: "HİSSE", forbidden: ["Pay", "Borsa", "Şirket", "Ortak", "Senet"] },
  { target: "BORSA", forbidden: ["Hisse", "Para", "Yatırım", "Düşmek", "Yükselmek"] },
  { target: "DÖVİZ", forbidden: ["Para", "Yabancı", "Dolar", "Euro", "Kur"] },
  { target: "ALTIN", forbidden: ["Değerli", "Sarı", "Yatırım", "Takı", "Gram"] },
  { target: "FAİZ", forbidden: ["Banka", "Para", "Oran", "Kredi", "Borç"] },
  { target: "KREDİ", forbidden: ["Banka", "Borç", "Çekmek", "Ödemek", "Faiz"] },
  { target: "TAKSİT", forbidden: ["Ödeme", "Bölmek", "Ay", "Kart", "Borç"] },
  { target: "NAKİT", forbidden: ["Para", "Peşin", "Kağıt", "Ödeme", "Cüzdan"] },
  { target: "FATURA", forbidden: ["Ödeme", "Elektrik", "Su", "Borç", "Kağıt"] },
  { target: "FİŞ", forbidden: ["Alışveriş", "Kağıt", "Kasa", "Belge", "Fiyat"] },
  { target: "GARANTİ", forbidden: ["Belge", "Süre", "Tamir", "Koruma", "Ürün"] },
  { target: "İADE", forbidden: ["Geri", "Vermek", "Ürün", "Alışveriş", "Para"] },
  { target: "İNDİRİM", forbidden: ["Ucuz", "Fiyat", "Düşmek", "Yüzde", "Kampanya"] },
  { target: "KAMPANYA", forbidden: ["Fırsat", "Reklam", "Ucuz", "Satış", "Promosyon"] },
  { target: "REKLAM", forbidden: ["Tanıtım", "Televizyon", "Ürün", "Satış", "İzlemek"] },
  { target: "MARKA", forbidden: ["İsim", "Logo", "Kalite", "Firma", "Ürün"] },
  { target: "LOGO", forbidden: ["Simge", "Resim", "Marka", "Şekil", "Tasarım"] },
  { target: "SLOGAN", forbidden: ["Söz", "Cümle", "Reklam", "Akılda", "Marka"] },
  { target: "VİZYON", forbidden: ["Gelecek", "Bakış", "Hedef", "Görüş", "Şirket"] },
  { target: "MİSYON", forbidden: ["Amaç", "Görev", "Şirket", "Hedef", "Yapmak"] },

  // --- YENİ EKLENEN ÇOK ZOR KELİMELER (SOYUT & KAVRAMSAL) (~135 ADET) ---
  { target: "PARADOKS", forbidden: ["Çelişki", "Mantık", "Döngü", "İmkansız", "Zaman"] },
  { target: "DEJAVU", forbidden: ["An", "Yaşamak", "Tekrar", "His", "Görmek"] },
  { target: "NOSTALJİ", forbidden: ["Geçmiş", "Özlem", "Eski", "Hatıra", "Mazi"] },
  { target: "MELANKOLİ", forbidden: ["Hüzün", "Mutsuzluk", "Duygu", "Keder", "Depresyon"] },
  { target: "ÜTOPYA", forbidden: ["Hayal", "Mükemmel", "Dünya", "Gelecek", "İmkansız"] },
  { target: "DİSTOPYA", forbidden: ["Kötü", "Gelecek", "Karanlık", "Toplum", "Film"] },
  { target: "EMPATİ", forbidden: ["Kendini", "Yerine", "Koymak", "Hissetmek", "Anlamak"] },
  { target: "KAOS", forbidden: ["Karmaşa", "Düzen", "Kargaşa", "Teori", "Karışık"] },
  { target: "SÜRREALİZM", forbidden: ["Gerçeküstü", "Sanat", "Dali", "Resim", "Akım"] },
  { target: "METAFOR", forbidden: ["Benzetme", "Edebiyat", "Anlam", "Söz", "Mecaz"] },
  { target: "İRONİ", forbidden: ["Alay", "Ters", "Söylemek", "Komik", "Durum"] },
  { target: "BİLİNÇALTI", forbidden: ["Rüya", "Freud", "Zihin", "Psikoloji", "Düşünce"] },
  { target: "EGO", forbidden: ["Benlik", "Kibir", "Kendini", "Psikoloji", "Üstün"] },
  { target: "HALÜSİNASYON", forbidden: ["Görmek", "Hayal", "Gerçek", "Olmayan", "Sanrı"] },
  { target: "İLLÜZYON", forbidden: ["Sihirbaz", "Göz", "Yanılsama", "Gerçek", "Numara"] },
  { target: "HİPNOZ", forbidden: ["Uyku", "Telkin", "Saat", "Bilinç", "Kontrol"] },
  { target: "TELEPATİ", forbidden: ["Zihin", "Okumak", "Düşünce", "İletişim", "Beyin"] },
  { target: "KUANTUM", forbidden: ["Fizik", "Atom", "Mekanik", "Küçük", "Enerji"] },
  { target: "GÖRELİLİK", forbidden: ["Einstein", "Zaman", "Hız", "İzafiyet", "Teori"] },
  { target: "EVRİM", forbidden: ["Darwin", "Maymun", "Değişim", "Biyoloji", "Tür"] },
  { target: "YERÇEKİMİ", forbidden: ["Newton", "Elma", "Düşmek", "Uzay", "Dünya"] },
  { target: "ATMOSFER", forbidden: ["Hava", "Tabaka", "Dünya", "Uzay", "Gaz"] },
  { target: "FOTOSENTEZ", forbidden: ["Bitki", "Güneş", "Yeşil", "Besin", "Yaprak"] },
  { target: "ENFLASYON", forbidden: ["Para", "Fiyat", "Artış", "Ekonomi", "Zam"] },
  { target: "DEMOKRASİ", forbidden: ["Halk", "Seçim", "Oy", "Yönetim", "Sandık"] },
  { target: "ADALET", forbidden: ["Mahkeme", "Terazi", "Hukuk", "Hakim", "Eşitlik"] },
  { target: "BÜROKRASİ", forbidden: ["Devlet", "Kağıt", "İş", "Memur", "Yavaş"] },
  { target: "SANSÜR", forbidden: ["Yasak", "Kısıtlama", "Basın", "Haber", "Gizlemek"] },
  { target: "PROPAGANDA", forbidden: ["Siyaset", "Reklam", "Fikir", "Yaymak", "Etki"] },
  { target: "KÜRESEL ISINMA", forbidden: ["İklim", "Sıcak", "Buzul", "Dünya", "Erimek"] },
  { target: "GERİ DÖNÜŞÜM", forbidden: ["Çöp", "Plastik", "Kağıt", "Kutu", "Tekrar"] },
  { target: "EKOLOJİ", forbidden: ["Çevre", "Doğa", "Bilim", "Canlı", "Denge"] },
  { target: "ARKEOLOJİ", forbidden: ["Kazı", "Tarih", "Eski", "Kemik", "Eser"] },
  { target: "MİTOLOJİ", forbidden: ["Tanrı", "Efsane", "Yunan", "Zeus", "Hikaye"] },
  { target: "ASTRONOMİ", forbidden: ["Uzay", "Yıldız", "Gezegen", "Bilim", "Teleskop"] },
  { target: "VİRTÜÖZ", forbidden: ["Müzik", "Usta", "Çalmak", "Enstrüman", "Yetenek"] },
  { target: "ESTETİK", forbidden: ["Güzellik", "Sanat", "Ameliyat", "Görünüş", "Felsefe"] },
  { target: "KOREOGRAFİ", forbidden: ["Dans", "Hareket", "Sahne", "Düzen", "Grup"] },
  { target: "SENARYO", forbidden: ["Film", "Yazı", "Hikaye", "Oyuncu", "Metin"] },
  { target: "KARİKATÜR", forbidden: ["Çizim", "Komik", "Mizah", "Baloncuk", "Gazete"] },
  { target: "NİHİLİZM", forbidden: ["Hiçlik", "Felsefe", "Anlam", "İnanç", "Yok"] },
  { target: "VAROLUŞÇULUK", forbidden: ["Felsefe", "İnsan", "Anlam", "Yaşam", "Sartre"] },
  { target: "KARMA", forbidden: ["Felsefe", "Etki", "Tepki", "İyilik", "Kötülük"] },
  { target: "NİRVANA", forbidden: ["Huzur", "Budizm", "Ulaşmak", "Tepe", "Aydınlanma"] },
  { target: "AURA", forbidden: ["Enerji", "Etki", "Işık", "Kişi", "His"] },
  { target: "BOYUT", forbidden: ["Uzay", "Zaman", "Ölçü", "3D", "Evren"] },
  { target: "PARALEL EVREN", forbidden: ["Dünya", "Başka", "Yaşam", "Teori", "Gerçek"] },
  { target: "ZAMAN YOLCULUĞU", forbidden: ["Geçmiş", "Gelecek", "Makine", "Bilim Kurgu", "Gitmek"] },
  { target: "KELEBEK ETKİSİ", forbidden: ["Kaos", "Küçük", "Büyük", "Sonuç", "Olay"] },
  { target: "SİMÜLASYON", forbidden: ["Gerçek", "Yapay", "Bilgisayar", "Dünya", "Matrix"] },
  { target: "SONSUZLUK", forbidden: ["Bitmeyen", "Zaman", "Uzay", "Ebedi", "İşaret"] },
  { target: "HİÇLİK", forbidden: ["Boşluk", "Yok", "Varlık", "Karanlık", "Anlam"] },
  { target: "BİLİNÇ", forbidden: ["Farkında", "Akıl", "Zihin", "Uyanık", "Beyin"] },
  { target: "RUH", forbidden: ["Beden", "Can", "Ölüm", "Hayalet", "İç"] },
  { target: "KADER", forbidden: ["Yazgı", "Hayat", "Gelecek", "Alın Yazısı", "Değişmez"] },
  { target: "ŞANS", forbidden: ["Talih", "Kısmet", "Oyun", "İyi", "Rastgele"] },
  { target: "TESADÜF", forbidden: ["Rastlantı", "Karşılaşmak", "Plan", "Olay", "Denk"] },
  { target: "GİZEM", forbidden: ["Sır", "Bilinmeyen", "Merak", "Olay", "Çözmek"] },
  { target: "MUAMMA", forbidden: ["Bilinmez", "Zor", "Durum", "Karışık", "Soru"] },
  { target: "RİTÜEL", forbidden: ["Tören", "Adet", "Tekrar", "İnanç", "Yapmak"] },
  { target: "SEMBOl", forbidden: ["İşaret", "Simge", "Anlam", "Resim", "Temsil"] },
  { target: "KEHANET", forbidden: ["Gelecek", "Söylemek", "Büyü", "Kahin", "Tahmin"] },
  { target: "SEZGİ", forbidden: ["His", "İç", "Bilmek", "Tahmin", "Duygu"] },
  { target: "İLHAM", forbidden: ["Fikir", "Sanat", "Gelmek", "Yaratıcılık", "Perisi"] },
  { target: "VİCDAN", forbidden: ["İç Ses", "Ahlak", "Rahat", "Azap", "İyi"] },
  { target: "ETİK", forbidden: ["Ahlak", "Doğru", "Yanlış", "Kural", "Davranış"] },
  { target: "TABU", forbidden: ["Yasak", "Oyun", "Kelimeler", "Konuşmak", "Toplum"] },
  { target: "DOGMA", forbidden: ["İnanç", "Sorgulamak", "Kesin", "Düşünce", "Kural"] },
  { target: "ÖNYARGI", forbidden: ["Peşin", "Hüküm", "Düşünce", "Tanımadan", "Kötü"] },
  { target: "STEREOTİP", forbidden: ["Kalıp", "Düşünce", "Genelleme", "Toplum", "Özellik"] },
  { target: "MANİPÜLASYON", forbidden: ["Yönlendirme", "Etki", "Kandırmak", "Kontrol", "Psikoloji"] },
  { target: "NARSİST", forbidden: ["Kendini", "Sevmek", "Aşık", "Bencil", "Ego"] },
  { target: "DEPRESYON", forbidden: ["Üzüntü", "Hastalık", "Mutsuz", "Ruh", "Tedavi"] },
  { target: "ANKSİYETE", forbidden: ["Kaygı", "Korku", "Endişe", "Panik", "Hastalık"] },
  { target: "TRAVMA", forbidden: ["Olay", "Geçmiş", "Etki", "Kötü", "Psikoloji"] },
  { target: "KOMPLEKS", forbidden: ["Karmaşık", "Aşağılık", "Psikoloji", "Sorun", "Duygu"] },
  { target: "LİBİDO", forbidden: ["Enerji", "Cinsel", "İstek", "Freud", "Dürtü"] },
  { target: "ARZU", forbidden: ["İstek", "Tutku", "Dilek", "İstemek", "Güçlü"] },
  { target: "HAZZ", forbidden: ["Zevk", "Mutluluk", "Duygu", "Keyif", "Almak"] },
  { target: "MELODRAM", forbidden: ["Abartı", "Duygu", "Film", "Ağlamak", "Olay"] },
  { target: "TRAJEDİ", forbidden: ["Üzücü", "Olay", "Son", "Tiyatro", "Dram"] },
  { target: "KOMEDİ", forbidden: ["Gülmek", "Eğlence", "Film", "Mizah", "Şaka"] },
  { target: "KASVET", forbidden: ["Sıkıntı", "Karanlık", "Hava", "İç", "Basmak"] },
  { target: "HUZUR", forbidden: ["Sakin", "Mutlu", "Sessiz", "Rahat", "Barış"] },
  { target: "COŞKU", forbidden: ["Heyecan", "Sevinç", "Yüksek", "Kutlama", "Enerji"] },
  { target: "İHTİRAS", forbidden: ["Tutku", "Arzu", "Güçlü", "İstek", "Aşk"] },
  { target: "KISKANÇLIK", forbidden: ["Çekememek", "Sevgili", "Başarı", "Haset", "Duygu"] },
  { target: "İHANET", forbidden: ["Aldatmak", "Güven", "Arkadan", "Bıçaklamak", "Yalan"] },
  { target: "SADAKAT", forbidden: ["Bağlılık", "Güven", "Söz", "Dost", "Eş"] },
  { target: "FEDAKARLIK", forbidden: ["Vermek", "Kendinden", "Yapmak", "Özveri", "Zor"] },
  { target: "CESARET", forbidden: ["Korkmamak", "Yürek", "Kahraman", "Atılmak", "Güç"] },
  { target: "ALÇAKGÖNÜLLÜ", forbidden: ["Mütevazı", "Kibir", "Ego", "Sade", "İnsan"] },
  { target: "KİBİR", forbidden: ["Büyüklenmek", "Ego", "Üstün", "Gurur", "Kendini"] },
  { target: "ÖZGÜRLÜK", forbidden: ["Hür", "Bağımsız", "Kuş", "Hapis", "İrade"] },
  { target: "ESARET", forbidden: ["Tutsak", "Hapis", "Köle", "Özgür", "Bağlı"] },
  { target: "DEVRİM", forbidden: ["Değişim", "Yenilik", "Hızlı", "Siyasi", "Düzen"] },
  { target: "ANARŞİ", forbidden: ["Kaos", "Düzen", "Devlet", "Kural", "Yok"] },
  { target: "FAŞİZM", forbidden: ["Baskı", "Yönetim", "Diktatör", "Siyaset", "Irk"] },
  { target: "KOMÜNİZM", forbidden: ["Eşitlik", "Ortak", "Devlet", "Siyaset", "Marx"] },
  { target: "KAPİTALİZM", forbidden: ["Para", "Sermaye", "Piyasa", "Ekonomi", "ABD"] },
  { target: "GLOBALLEŞME", forbidden: ["Dünya", "Küresel", "Tek", "Pazar", "İletişim"] },
  { target: "MEDENİYET", forbidden: ["Uygarlık", "Kültür", "Gelişmiş", "Toplum", "Şehir"] },
  { target: "KÜLTÜR", forbidden: ["Sanat", "Gelenek", "Yaşam", "Toplum", "Bilgi"] },
  { target: "SANAT", forbidden: ["Resim", "Müzik", "Yaratıcılık", "Eser", "Güzellik"] },
  { target: "BİLİM", forbidden: ["Deney", "Araştırma", "Gerçek", "Bilgi", "Teknoloji"] },
  { target: "FELSEFE", forbidden: ["Düşünce", "Soru", "Sokrates", "Bilgi", "Aramak"] },
  { target: "TARİH", forbidden: ["Geçmiş", "Olay", "Zaman", "Eski", "Ders"] },
  { target: "COĞRAFYA", forbidden: ["Yer", "Harita", "Dünya", "Dağ", "Deniz"] },
];

// Sessiz Mod: Mevcut + Yeni Hareket Odaklı Kelimeler (~135 EYLEM)
const SILENT_POOL_STRINGS: string[] = [
  // MEVCUT NESNELER (~135 ADET)
  "Diş Fırçası", "Direksiyon", "Ütü", "Olta", "Yastık", 
  "Kitap", "Telefon", "Havlu", "Kaşık", "Bardak",
  "Ayakkabı", "Gözlük", "Gitar", "Davul", "Piyano",
  "Fotoğraf Makinesi", "Tarak", "Ruj", "Tıraş Makinesi",
  "Süpürge", "Bez", "Tencere", "Bebek", 
  "İp", "Bisiklet", "Top", "Basketbol Topu",
  "Raket", "Boks Eldiveni", "Halter", "Ok ve Yay", "Balon",
  "Sakız", "Dondurma", "Çay Bardağı", "Çorba Kasesi", 
  "Uçurtma", "İğne İplik", "Örgü Şişi", "Kalem", "Fırça", 
  "Heykel", "Mikrofon", "Kuş Yemi", "Tasmalı Köpek", 
  "At", "İnek", "Tavuk", "Balta", "Kibrit", 
  "Çadır", "Balık", "Maymun", "Yılan", "Kuş", 
  "Fil", "Aslan", "Tavşan", "Kanguru", "Penguen", 
  "Robot", "Zombi", "Hayalet", "Vampir", "Uçak", 
  "Helikopter", "Korna", "Zil", 
  "Saat", "Şemsiye", "Kardan Adam", "Kayak", "Paten", 
  "Dalgıç Tüpü", "Paraşüt", "Sırt Çantası", 
  "Mangal", "Hediye Paketi", "Mum", "Pasta", "Düğme", 
  "Fermuar", "Kravat", "Yüzük", "Küpe", 
  "Kolye", "Parfüm", "Saç Kurutma Makinesi", "Oje", 
  "Şapka", "Eldiven", "Atkı", 
  "Mont", "Terlik", "Çorap", "Yorgan", 
  "Pencere", "Perde", "Anahtar", "Lamba", 
  "Televizyon", "Kumanda", "Bilgisayar", "Klavye", 
  "Mouse", "Oyun Konsolu", "Selfie Çubuğu", "Kulaklık", 
  "Gazete", "Cüzdan", "Kredi Kartı", "Alışveriş Sepeti", 
  "Poşet", "Otobüs", "Taksi", "Metro", 
  "Emniyet Kemeri", "Vites", "Fren", 
  "Benzin Pompası", "Lastik", "Araba Motoru", 
  "Dürbün", "Harita", "Pusula", 
  "Halat", "Frizbi", "Kağıt Uçak", "Gemi", "Kumdan Kale", 
  "Şezlong", "Güneş Kremi", 
  "Merdiven", "Asansör", "Döner Kapı", 
  "Yara Bandı", "Hap", "Ateş Ölçer", "Şırınga", 
  "Stetoskop", "Maske", "Dezenfektan", 
  "Düdük", "Madalya", "Kupa", "Bayrak",
  "Çekiç", "Çivi", "Testere", "Matkap", "Tornavida", "Pense", "Metre",
  "Kürek", "Tırmık", "El Arabası", "Sulama Kabı", "Hortum", "Saksı",
  "Biberon", "Emzik", "Bebek Arabası", "Mama Önlüğü", "Beşik",
  "Bavul", "Pasaport", "Uçak Bileti", 
  "Mikroskop", "Teleskop", "Büyüteç", "Terazi",
  "Kasa", "Para", "Altın", "Elmas", 
  "Polis Rozeti", "Kelepçe", "Telsiz", "Cop",
  "İtfaiye Hortumu", "Yangın Tüpü", "Kask", "Çizme",
  "Aşçı Şapkası", "Önlük", "Kepçe", "Rende", "Çırpıcı",
  "Oklava", "Elek", "Huni", "Konserve Açacağı",
  "Tuzluk", "Biberlik", "Peçete", "Kürdan",
  "Sabun", "Şampuan", "Lif", "Bornoz", 
  "Diş Macunu", "Diş İpi", "Kulak Çubuğu",
  "Ayna", "Cımbız", "Makas", "Törpü",
  "Vantilatör", "Klima", "Soba", "Şömine",
  "Ütü Masası", "Çamaşır Sepeti", "Mandal",
  "Askı", "Ayakkabılık", "Vestiyer",
  "Tabure", "Koltuk", "Kanepe", "Sandalye",
  "Masa", "Sehpa", "Kitaplık", "Raf",
  "Yatak", "Ranza", "Beşik", "Hamak",
  "Salıncak", "Kaydırak", "Tahterevalli",
  "Kumbara", "Mücevher Kutusu",
  "Dikiş Makinesi", "Mezura", "Yüksük",
  "Pipo", "Baston", "Gözlük Kılıfı",
  "Sigara", "Çakmak", "Küllük",
  "Tespih", "Seccade", "Kuran",
  "Gitar Kılıfı", "Nota Sehpası", "Baget",
  "Mikrofon Ayağı", "Hoparlör", "Amfi",
  "Projeksiyon", "Perde", "Yazı Tahtası", "Silgi", "Tebeşir",
  "Zımba", "Delgeç", "Ataş", "Bant", "Yapıştırıcı",
  "Dosya", "Klasör", "Zarf", "Mektup",
  "Pul", "Damga", "Mürekkep", "Dolma Kalem",
  "Daktilo", "Faks", "Fotokopi Makinesi",
  "Hesap Makinesi", "Takvim", "Ajanda",

  // --- YENİ EKLENEN HAREKET ODAKLI ZOR KELİMELER (~135 ADET) ---
  "Selfie Çekmek", "Halay Çekmek", "Yoga Yapmak", "Meditasyon", "Moonwalk Yapmak",
  "Bungee Jumping", "Paraşütle Atlamak", "Sörf Yapmak", "Kaykay Sürmek",
  "Bowling Oynamak", "Golf Oynamak", "Bilardo Oynamak", "Dart Atmak",
  "Satranç Oynamak", "Balık Tutmak", "Kamp Yapmak", "Ateş Yakmak",
  "Odun Kesmek", "Çivi Çakmak", "Duvar Boyamak", "Araba Yıkamak",
  "Lastik Değiştirmek", "Benzin Doldurmak", "Otostop Çekmek",
  "Ameliyat Yapmak", "Diş Çekmek", "Tansiyon Ölçmek", "İğne Yapmak",
  "Pankek Çevirmek", "Hamur Açmak", "Soğan Doğramak", "Yumurta Kırmak",
  "Bulaşık Yıkamak", "Çamaşır Asmak", "Ütü Yapmak", "Yer Silmek", "Cam Silmek",
  "Bebek Uyutmak", "Bebek Altı Değiştirmek", "Gaz Çıkarmak",
  "Saç Taramak", "Makyaj Yapmak", "Oje Sürmek", "Parfüm Sıkmak",
  "Kravat Bağlamak", "Ayakkabı Bağlamak", "Düğme İliklemek",
  "Hapşırmak", "Öksürmek", "Esnemek", "Horlamak", "Kaşınmak",
  "Üşümek", "Terlemek", "Ağlamak", "Gülmek", "Korkmak", "Şaşırmak",
  "Düşünmek", "Unutmak", "Hatırlamak", "Aşık Olmak", "Küsmek",
  "Telefonla Konuşmak", "Mesaj Yazmak", "Bilgisayar Oyunu Oynamak",
  "Film İzlemek", "Kitap Okumak", "Yazı Yazmak", "Resim Çizmek",
  "Şarkı Söylemek", "Dans Etmek", "Islık Çalmak", "Alkışlamak",
  "Selamlaşmak", "El Sıkışmak", "Sarılmak", "Öpmek",
  "Koşmak", "Yürümek", "Zıplamak", "Emeklemek", "Yüzmek", "Dalmak",
  "Tırmanmak", "Düşmek", "Bayılmak", "Boğulmak", "Yanmak", "Donmak",
  "Oturmak", "Kalkmak", "Yatmak", "Uyumak", "Uyanmak",
  "Durmak", "Beklemek", "Bakmak", "Görmek", "Duymak", "Dinlemek",
  "Koklamak", "Tatmak", "Yemek", "İçmek", "Çiğnemek", "Yutmak", "Kusmak",
  "Gerinmek", "Giyinmek", "Soyunmak", "Titremek",
  "Bağırmak", "Fısıldamak", "Susmak", "Anlamak", "Bilmek",
  "İnanmak", "Sevmek", "Nefret Etmek", "İstemek", "İstememek",
  "Almak", "Vermek", "Tutmak", "Bırakmak", "Atmak", "Yakalamak",
  "İtmek", "Çekmek", "Kaldırmak", "İndirmek", "Taşımak", "Koymak",
  "Açmak", "Kapatmak", "Kilitlemek", "Anahtarlamak", "Çalmak",
  "Söylemek", "Okumak", "Kesmek", "Yapıştırmak", "Dikmek", "Örmek",
  "Pişirmek", "Temizlemek", "Süpürmek", "Tamir Etmek",
  "Bozulmak", "Kırılmak", "Çarpmak", "Vurmak", "Dövmek",
  "Kavga Etmek", "Barışmak", "Vedalaşmak", "Dua Etmek",
  "İbadet Etmek", "Secde Etmek", "Rüku Etmek", "Abdest Almak",
  "Tıraş Olmak", "Duş Almak", "Liflenmek", "Keselemek",
  "Krem Sürmek", "Güneşlenmek", "Yanmak (Güneş)", "Serinlemek",
  "Yelpazelenmek", "Terini Silmek", "Su İçmek", "Boğulur Gibi Olmak",
  "Nefes Almak", "Nefes Vermek", "Nefesini Tutmak", "Şişmek", "Patlamak"
];

// Maraton Modu: Mevcut + Yeni Bilimsel/Akademik Kelimeler (~230 ADET)
const MARATHON_POOL_STRINGS: string[] = [
  // MEVCUT GENEL KELİMELER (~230 ADET)
  "Masa", "Sandalye", "Kalem", "Kağıt", "Silgi", "Defter", "Kitap", "Çanta", "Ayakkabı", "Çorap",
  "Gömlek", "Pantolon", "Ceket", "Şapka", "Gözlük", "Saat", "Telefon", "Bilgisayar", "Fare", "Klavye",
  "Ekran", "Kamera", "Mikrofon", "Kulaklık", "Hoparlör", "Lamba", "Ampul", "Priz", "Kablo", "Pil",
  "Kumanda", "Televizyon", "Radyo", "Buzdolabı", "Fırın", "Ocak", "Tencere", "Tava", "Çatal", "Kaşık",
  "Bıçak", "Tabak", "Bardak", "Şişe", "Kapak", "Kutu", "Koli", "Poşet", "Çöp", "Süpürge",
  "Paspas", "Kova", "Sabun", "Şampuan", "Havlu", "Ayna", "Tarak", "Fırça", "Macun", "Musluk",
  "Kapı", "Pencere", "Perde", "Halı", "Koltuk", "Yastık", "Yorgan", "Çarşaf", "Yatak", "Dolap",
  "Çekmece", "Raf", "Askı", "Anahtar", "Kilit", "Cüzdan", "Para", "Kart", "Bilet", "Pasaport",
  "Kimlik", "Dosya", "Zarf", "Mektup", "Pul", "Bant", "Makas", "Yapıştırıcı", "Zımba", "Delgeç",
  "Ataş", "Raptiye", "Cetvel", "Pergel", "Hesap Makinesi", "Takvim", "Harita", "Küre", "Bayrak", "Rozet",
  "Kemer", "Toka", "Yüzük", "Kolye", "Küpe", "Bilezik", "Saat", "Gözlük", "Şemsiye", "Baston",
  "Eldiven", "Atkı", "Bere", "Mont", "Kaban", "Yağmurluk", "Çizme", "Terlik", "Sandalet", "Spor Ayakkabı",
  "Top", "Balon", "Uçurtma", "Oyuncak", "Bebek", "Araba", "Tren", "Uçak", "Gemi", "Bisiklet",
  "Kaykay", "Paten", "Kask", "Dizlik", "Raket", "File", "Kale", "Pota", "Düdük", "Madalya",
  "Kupa", "Bayrak", "Flama", "Balık", "Kedi", "Köpek", "Kuş", "Tavşan", "Fare", "At",
  "İnek", "Koyun", "Keçi", "Tavuk", "Horoz", "Ördek", "Kaz", "Arı", "Kelebek", "Sinek",
  "Böcek", "Örümcek", "Yılan", "Kaplumbağa", "Balina", "Yunus", "Köpek Balığı", "Ahtapot", "Yengeç", "Deniz Yıldızı",
  "Ağaç", "Çiçek", "Gül", "Papatya", "Lale", "Yaprak", "Dal", "Kök", "Ot", "Çim",
  "Toprak", "Taş", "Kaya", "Kum", "Çakıl", "Dağ", "Tepe", "Ova", "Orman", "Göl",
  "Nehir", "Deniz", "Okyanus", "Ada", "Kıta", "Ülke", "Şehir", "Köy", "Kasaba", "Mahalle",
  "Sokak", "Cadde", "Park", "Bahçe", "Bina", "Ev", "Okul", "Hastane", "Postane", "Banka",
  "Market", "Fırın", "Kasap", "Manav", "Eczane", "Kuaför", "Berber", "Terzi", "Tamirci", "Fabrika",
  "Ofis", "Büro", "Dükkan", "Mağaza", "AVM", "Sinema", "Tiyatro", "Müze", "Kütüphane", "Stadyum",
  "Spor Salonu", "Havuz", "Plaj", "Liman", "Havaalanı", "Terminal", "Durak", "İstasyon", "Gar", "Köprü",
  "Tünel", "Yol", "Kaldırım", "Lamba", "Trafik Işığı", "Levha", "Tabela", "Reklam", "Afiş", "Poster",
  "Resim", "Tablo", "Heykel", "Vazo", "Saksı", "Çerçeve", "Fotoğraf", "Albüm", "Kamera", "Film",
  "Müzik", "Şarkı", "Nota", "Gitar", "Piyano", "Keman", "Davul", "Flüt", "Saz", "Mikrofon",
  "Hoparlör", "Kulaklık", "Radyo", "Televizyon", "Bilgisayar", "Tablet", "Telefon", "Saat", "Pil", "Fener",
  "Mum", "Kibrit", "Çakmak", "Ateş", "Duman", "Kül", "Odun", "Kömür", "Sob", "Kalorifer",
  "Klima", "Vantilatör", "Pervane", "Motor", "Tekerlek", "Direksiyon", "Vites", "Fren", "Gaz", "Debriyaj",
  "Ayna", "Cam", "Kapı", "Bagaj", "Koltuk", "Emniyet Kemeri", "Hava Yastığı", "Silecek", "Plaka", "Tampon",
  "Far", "Sinyal", "Stop", "Lastik", "Jant", "Sibop", "Zincir", "Yağ", "Benzin", "Mazot",
  "LPG", "İstasyon", "Pompa", "Fiş", "Fatura", "Para", "Kredi Kartı", "Banka Kartı", "Cüzdan", "Çanta",
  "Kasa", "Anahtar", "Kilit", "Alarm", "Güvenlik", "Kamera", "Polis", "Jandarma", "Bekçi", "Zabıta",
  "Doktor", "Hemşire", "Hasta", "Ambulans", "Sedyre", "İlaç", "Hap", "Şurup", "İğne", "Aşı",
  "Sargı", "Bant", "Pamuk", "Alkol", "Derece", "Tansiyon Aleti", "Stetoskop", "Önlük", "Maske", "Eldiven",
  "Öğretmen", "Öğrenci", "Müdür", "Hademe", "Sınıf", "Sıra", "Masa", "Tahta", "Tebeşir", "Silgi",
  "Kalem", "Defter", "Kitap", "Sözlük", "Ansiklopedi", "Harita", "Küre", "Cetvel", "Pergel", "İletki",
  "Çanta", "Beslenme", "Suluk", "Önlük", "Forma", "Eşofman", "Spor", "Ders", "Teneffüs", "Zil",
  "Sınav", "Not", "Karne", "Diploma", "Mezuniyet", "Kep", "Cübbe", "Üniversite", "Fakülte", "Kampüs",
  "Yurt", "Kantin", "Yemekhane", "Kafeterya", "Restoran", "Lokanta", "Büfe", "Çay Ocağı", "Kahve", "Çay",
  "Şeker", "Tuz", "Biber", "Baharat", "Yağ", "Un", "Ekmek", "Peynir", "Zeytin", "Yumurta",

  // --- YENİ EKLENEN ZOR/BİLİMSEL KELİMELER (~230 ADET) ---
  "Algoritma", "Yazılım", "Donanım", "İşletim Sistemi", "Veritabanı", "Sunucu", "Bulut",
  "İnternet", "Wifi", "Bluetooth", "Fiber", "Uydu", "Frekans", "Radyasyon", "Enerji",
  "Elektrik", "Manyetizma", "Yerçekimi", "Kütle", "Hız", "İvme", "Kuvvet", "Basınç",
  "Sıcaklık", "Isı", "Atom", "Molekül", "Hücre", "DNA", "Gen", "Kromozom",
  "Bakteri", "Virüs", "Organ", "Doku", "İskelet", "Kas", "Sinir", "Beyin",
  "Kalp", "Akciğer", "Mide", "Karaciğer", "Böbrek", "Damar", "Kan", "Bağışıklık",
  "Psikoloji", "Sosyoloji", "Felsefe", "Tarih", "Coğrafya", "Edebiyat", "Matematik",
  "Fizik", "Kimya", "Biyoloji", "Astronomi", "Jeoloji", "Arkeoloji", "Antropoloji",
  "Ekonomi", "Politika", "Hukuk", "Sanat", "Müzik", "Resim", "Heykel", "Mimari",
  "Sinema", "Tiyatro", "Opera", "Bale", "Dans", "Spor", "Futbol", "Basketbol",
  "Voleybol", "Tenis", "Yüzme", "Atletizm", "Jimnastik", "Olimpiyat", "Şampiyona",
  "Kupa", "Madalya", "Rekor", "Hakem", "Antrenör", "Taraftar", "Stadyum",
  "Demokrasi", "Cumhuriyet", "Monarşi", "Diktatörlük", "Anayasa", "Meclis", "Seçim",
  "Parti", "Lider", "Başkan", "Bakan", "Milletvekili", "Belediye", "Vali",
  "Diplomasi", "Savaş", "Barış", "Anlaşma", "İttifak", "Birleşmiş Milletler", "Avrupa Birliği",
  "Nato", "Ekonomi", "Enflasyon", "Faiz", "Döviz", "Borsa", "Yatırım", "Ticaret",
  "İhracat", "İthalat", "Vergi", "Bütçe", "Borç", "Kriz", "Kalkınma",
  "Kültür", "Medeniyet", "Gelenek", "Görenek", "Din", "İnanç", "İbadet",
  "Camii", "Kilise", "Havra", "Tapınak", "Bayram", "Festival", "Tören",
  "İletişim", "Medya", "Gazete", "Televizyon", "Radyo", "İnternet", "Sosyal Medya",
  "Reklam", "Halkla İlişkiler", "Gazetecilik", "Yayıncılık", "Telif Hakkı", "Sansür",
  "Ulaşım", "Trafik", "Otoyol", "Köprü", "Tünel", "Havalimanı", "Liman", "Gar",
  "Turizm", "Otel", "Tatil", "Seyahat", "Rehber", "Pasaport", "Vize",
  "Sanayi", "Fabrika", "Üretim", "Hammadde", "Enerji", "Petrol", "Doğalgaz",
  "Tarım", "Çiftçi", "Toprak", "Hasat", "Sulama", "Gübre", "Tohum",
  "Hayvancılık", "Besicilik", "Süt", "Et", "Yün", "Deri", "Balıkçılık",
  "Metropol", "Nüfus", "Göç", "Mülteci", "Vatandaş", "Sınır", "Gümrük",
  "İklim", "Çevre", "Doğa", "Kirlilik", "Atık", "Sürdürülebilirlik", "Yenilenebilir",
  "Evren", "Galaksi", "Yıldız", "Gezegen", "Uydu", "Meteor", "Kuyruklu Yıldız",
  "Kara Delik", "Süpernova", "Nebula", "Işık Yılı", "Big Bang", "Gökbilim", "Teleskop",
  "Element", "Bileşik", "Karışım", "Asit", "Baz", "Tuz", "Metal",
  "Ametal", "Soygaz", "Periyodik Tablo", "Reaksiyon", "Katalizör", "Laboratuvar", "Deney",
  "Hipotez", "Teori", "Kanun", "Paradoks", "Aksiyom", "Teorem", "İspat",
  "Formül", "Denklem", "Fonksiyon", "Türev", "İntegral", "Logaritma", "Trigonometri",
  "Geometri", "Cebir", "İstatistik", "Olasılık", "Sayı", "Rakam", "Sıfır",
  "Sonsuzluk", "Limit", "Matris", "Vektör", "Koordinat", "Grafik", "Tablo",
  "Roman", "Hikaye", "Şiir", "Masal", "Destan", "Efsane", "Mitoloji",
  "Yazar", "Şair", "Eser", "Karakter", "Kurgu", "Tema", "Ana Fikir",
  "Dilbilgisi", "Sözcük", "Cümle", "Paragraf", "Noktalama", "Yazım", "Alfabe",
  "Sessiz Harf", "Sesli Harf", "Hece", "Kök", "Ek", "Fiil", "İsim",
  "Sıfat", "Zamir", "Zarf", "Edat", "Bağlaç", "Ünlem", "Deyim",
  "Atasözü", "Mecaz", "Gerçek", "Yan", "Terim", "Eş Anlam", "Zıt Anlam",
  "Müze", "Sergi", "Galeri", "Koleksiyon", "Antika", "Restorasyon", "Müzayede",
  "Bale", "Opera", "Orkestra", "Koro", "Şef", "Solist", "Besteci",
  "Enstrüman", "Nota", "Ritim", "Melodi", "Armoni", "Akor", "Gam",
  "Tuval", "Fırça", "Boya", "Palet", "Şövale", "Eskiz", "Portre"
];

// --- YARDIMCI FONKSİYONLAR ---

// Fisher-Yates Shuffle Algorithm (Diziyi rastgele karıştırır)
function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

// --- ANA FONKSİYON ---

export const fetchTabuCards = async (mode: GameMode, previousWords: string[], count: number = 10): Promise<TabuCard[]> => {
  // 1. Mod'a göre ham veriyi seç
  let rawData: TabuCard[] = [];

  if (mode === GameMode.CLASSIC) {
    rawData = [...CLASSIC_POOL];
  } else if (mode === GameMode.SILENT) {
    rawData = SILENT_POOL_STRINGS.map(target => ({
      target,
      forbidden: ["KONUŞMAK YASAK!", "SES ÇIKARMAK YASAK!"],
      category: "Sessiz Sinema"
    }));
  } else if (mode === GameMode.MARATHON) {
    rawData = MARATHON_POOL_STRINGS.map(target => ({
      target,
      forbidden: ["Yasaklı Yok", "Hızlı Ol", "Kelime Say", "Pas Geçme", "Odaklan"], // Maraton modunda yasaklı kelime görünmez ama yapı bozulmasın diye ekledik
      category: "Maraton"
    }));
  }

  // 2. Daha önce kullanılmış kelimeleri çıkar
  const unusedData = rawData.filter(card => !previousWords.includes(card.target));

  // 3. Eğer havuzda yeterince kelime kalmadıysa, tüm havuzu tekrar kullan (Sonsuz döngü için)
  // Kullanıcıya hissettirmeden havuzu resetlemiş oluyoruz.
  const sourceData = unusedData.length < count ? rawData : unusedData;

  // 4. Havuzu karıştır
  const shuffledData = shuffleArray(sourceData);

  // 5. İstenen sayı kadar kelimeyi al ve döndür
  // Simüle edilmiş bir gecikme ekleyelim ki UI 'loading' durumunu göstersin (çok hızlı olursa glitch gibi durabilir)
  await new Promise(resolve => setTimeout(resolve, 300)); 

  return shuffledData.slice(0, count);
};
